### ISSUE TITLE
Run "status" will exit the user.py ...

### ISSUE THREAD

**Issue by ckl8964** [thoschm/START-Summit-2017-Blockchain-Machine-Learning-Workshop#6]
At the command line running "status" to view the user status will exit the program and show the error as follow 
**********************
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ethjsonrpc/client.py", line 115, in call
    data = self._encode_function(sig, args)
  File "/usr/local/lib/python2.7/dist-packages/ethjsonrpc/client.py", line 78, in _encode_function
    encoded_params = encode_abi(types, param_values)
  File "/usr/local/lib/python2.7/dist-packages/ethereum/abi.py", line 369, in encode_abi
    myhead += enc(proctypes[i], args[i])
  File "/usr/local/lib/python2.7/dist-packages/ethereum/abi.py", line 344, in enc
    return utils.to_string(encode_single(typ, arg))
  File "/usr/local/lib/python2.7/dist-packages/ethereum/abi.py", line 242, in encode_single
    raise EncodingError("Could not parse address: %r" % arg)
ethereum.abi.EncodingError: Could not parse address: u'0x5e4abd169eb165a21c06dd35f24055baabc716b8'
**********************

Any idea ?

**Comment by thoschm** [comment]
Hi, this is probably due to some (not backward compatible) changes in ethjsonrpc, I'll check at the weekend, a quick fix would be to try installing a previous version of it: pip install ethjsonrpc==set.version.here  but I have to check.
Thx for reporting!

**Comment by tenuki** [comment]
This also happens to my.. in my case it worked by removing initial 0x from address...
